# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    encrypt        = true
    key            = "prod/services/webserver-cluster/terraform.tfstate"
    region         = "us-east-1"
    bucket         = "terraform-up-and-running-state-cj-1"
    dynamodb_table = "terraform-state-lock-dynamo"
  }
}
